INSERT INTO MOVIE_REVIEW (COMMENTS,MOVIENAME,RATINGS,USERNAME) values ('good movie','Hang over', 4,'isuru'),
                                                                      ('Interesting movie', 'Hang over',5,'anjana'),
                                                                      ('One of the best feel good movies','Mr. Bean', 4,'isuru'),
                                                                      ('Full on garbage', 'F9',5,'anjana'),
                                                                      ('Best batman movie ever','The Dark Knight', 4,'isuru'),
                                                                      ('Batman reimagined. Great', 'The Dark Knight',5,'anjana'),
                                                                      ('Greatest horror movie ever','The Shining', 4,'isuru'),
                                                                      ('Very scary movie', 'The Shining',5,'anjana'),
                                                                      ('Mindblowing by Nolan','Tenet', 4,'isuru'),
                                                                      ('Hard to understand', 'Tenet',5,'anjana'),
                                                                      ('Entertaining thriller','Silence of the Lambs', 4,'isuru'),
                                                                      ('Great performance by actors', 'Silence of the Lambs',5,'anjana'),
                                                                      ('Best horror in 2010s','Us', 4,'isuru'),
                                                                      ('Very good movie', 'Us',5,'anjana'),
                                                                      ('Action packed and enjoyable','John Wick', 4,'isuru'),
                                                                      ('High octane fights', 'John Wick',5,'anjana'),
                                                                      ('Best work of Nolan','Inception', 4,'isuru'),
                                                                      ('Mind fully blown', 'Inception',5,'anjana'),
                                                                      ('Great action and fights','Mad Max', 4,'isuru'),
                                                                      ('Best achievement in horror history', 'The Exorcist',5,'isuru');